### PR TITLE
Ryan/feature/map layout styling

### LINKED ISSUE #76: Format map sizing

### LINKED ISSUE #77: Refactor filter button for map

### PR DESCRIPTION
**Pull request by Nagel29**
Type of change

- [x] New feature
- [x] Bug Fix
- [ ] Refactor

Implements/Fixes:
- Fixes map rendering issue where it was rendering partially blank
- Resizes map, rounds map corners. Size looks good on mobile view. May want to adjust for desktop, but mobile is top priority. 
- Moved `Filter` button to top left corner. I think this looks good for mobile view, but again may want to adjust for desktop.
- Adds `mapClickedRestaurant` to `restaurants` state
- `setMapClickedRestaurant` is dispatched on `Map` whenever a restaurant marker is clicked
- When `mapClickedRestaurant` is updated, `RestaurantList` automatically scrolls to the specific restaurant card
- Added 1 second timeout on scroll so the user could first see restaurant name on map

description closes issue #
Closes #77 
Closes #76

Checklist:

- [x] I have reviewed my code
- [x] My code has no unused/commented out code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have fully tested my code
- [ ] All Tests are Passing
- [x] The code will run locally

Please gif your feelings about this PR:

### CODE REVIEW

**Review by MattWalterTX — COMMENTED** [review]
Changes look good on my end locally.

**Comment by tricia-holmes** [comment]
@Nagel29 right now for me the scroll is happening right away! Could you comment on where the timeout is happening?

**Comment by Nagel29** [comment]
@tricia-holmes  It helps if I push that last commit up! My bad, should be there now

**Comment by tricia-holmes** [comment]
Thank you! I can see it now, and it looks good!

**Pull request merged**
